disable check for whther symbol is not yet defined for dynamic linking

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -126,20 +126,22 @@ EOF
     else
       LD_LIBRARY_PATH="$TMP_RAW_LD_LIB_PATH:$LD_LIBRARY_PATH" ./a.out > /dev/null 2>&1
     fi
-    if [ $IS_APPLE_CLANG -eq 0 ]; then
-      if [ $? -eq 0 ]; then
-        UDEFSYMB=$(nm ./a.out | grep "$3" | grep -c "U")
-        if [ $UDEFSYMB -eq 0 ]; then
-          status=1
-          if [ $4 -eq 1 ]; then
-              echo "Undefined symbol not found, so we did not really link to dynamic library (but rather static)"
-              ( set -x; nm ./a.out; )
-          fi
-        fi
-      else
-        status=0
-      fi
-    fi
+    # Check if symbol is not yet defined, to ensure we really linked to dynamic and not static
+    # Disabled because it seems this is not always a reliable check, things often work despite it failing
+    #if [ $IS_APPLE_CLANG -eq 0 ]; then
+    #  if [ $? -eq 0 ]; then
+    #    UDEFSYMB=$(nm ./a.out | grep "$3" | grep -c "U")
+    #    if [ $UDEFSYMB -eq 0 ]; then
+    #      status=1
+    #      if [ $4 -eq 1 ]; then
+    #          echo "Undefined symbol not found, so we did not really link to dynamic library (but rather static)"
+    #          ( set -x; nm ./a.out; )
+    #      fi
+    #    fi
+    #  else
+    #    status=0
+    #  fi
+    #fi
   fi
   rm -f .test.cxx a.out
   return $status
